/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TableeRouteImport } from './routes/tablee'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as SuiviRouteImport } from './routes/suivi'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as ProximiteRouteImport } from './routes/proximite'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as PopulaireRouteImport } from './routes/populaire'
import { Route as PartenaireRouteImport } from './routes/partenaire'
import { Route as ParrainageRouteImport } from './routes/parrainage'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as MboapassRouteImport } from './routes/mboapass'
import { Route as MboaAiRouteImport } from './routes/mboa-ai'
import { Route as LivreurRouteImport } from './routes/livreur'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as HealthcheckRouteImport } from './routes/healthcheck'
import { Route as FideliteRouteImport } from './routes/fidelite'
import { Route as FavorisRouteImport } from './routes/favoris'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as DevenirRestoRouteImport } from './routes/devenir-resto'
import { Route as DevenirLivreurRouteImport } from './routes/devenir-livreur'
import { Route as DecouvrirRouteImport } from './routes/decouvrir'
import { Route as CuisinesRouteImport } from './routes/cuisines'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CommandesRouteImport } from './routes/commandes'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as AideRouteImport } from './routes/aide'
import { Route as AdressesRouteImport } from './routes/adresses'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin.index'
import { Route as PartenaireIndexRouteImport } from './routes/partenaire.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TableePaiementRouteImport } from './routes/tablee.paiement'
import { Route as SuperadminSetup2faRouteImport } from './routes/superadmin_.setup-2fa'
import { Route as SuperadminLoginRouteImport } from './routes/superadmin_.login'
import { Route as SuperadminRestaurantsRouteImport } from './routes/superadmin.restaurants'
import { Route as SuperadminLivreursRouteImport } from './routes/superadmin.livreurs'
import { Route as SuiviOrderIdRouteImport } from './routes/suivi.$orderId'
import { Route as RestaurantsRestoIdRouteImport } from './routes/restaurants.$restoId'
import { Route as RestaurantConnexionRouteImport } from './routes/restaurant_.connexion'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as PartenaireRevenusRouteImport } from './routes/partenaire.revenus'
import { Route as PartenaireParametresRouteImport } from './routes/partenaire.parametres'
import { Route as PartenaireMenuRouteImport } from './routes/partenaire.menu'
import { Route as PartenaireCommandesRouteImport } from './routes/partenaire.commandes'
import { Route as LivreurConnexionRouteImport } from './routes/livreur_.connexion'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CompteSecuriteRouteImport } from './routes/compte.securite'
import { Route as ComptePaiementsRouteImport } from './routes/compte.paiements'
import { Route as CompteLivraisonRouteImport } from './routes/compte.livraison'
import { Route as CompteCommandesRouteImport } from './routes/compte.commandes'
import { Route as CategorieSlugRouteImport } from './routes/categorie.$slug'
import { Route as AideCategoryRouteImport } from './routes/aide.$category'
import { Route as AdminUnauthorizedRouteImport } from './routes/admin_.unauthorized'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminZonesRouteImport } from './routes/admin.zones'
import { Route as AdminRestaurantsRouteImport } from './routes/admin.restaurants'
import { Route as AdminParametresRouteImport } from './routes/admin.parametres'
import { Route as AdminMenusRouteImport } from './routes/admin.menus'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminLivreursRouteImport } from './routes/admin.livreurs'
import { Route as AdminLitigesRouteImport } from './routes/admin.litiges'
import { Route as AdminCommissionsRouteImport } from './routes/admin.commissions'
import { Route as AdminCommandesRouteImport } from './routes/admin.commandes'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as RestaurantsRestoIdMenuRouteImport } from './routes/restaurants.$restoId.menu'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicCampayWebhookRouteImport } from './routes/api/public/campay-webhook'
import { Route as RestaurantsRestoIdPlatsPlatIdRouteImport } from './routes/restaurants.$restoId_.plats.$platId'
import { Route as RSlugPlatsDishIdRouteImport } from './routes/r.$slug_.plats.$dishId'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const TableeRoute = TableeRouteImport.update({
  id: '/tablee',
  path: '/tablee',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviRoute = SuiviRouteImport.update({
  id: '/suivi',
  path: '/suivi',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const ProximiteRoute = ProximiteRouteImport.update({
  id: '/proximite',
  path: '/proximite',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const PopulaireRoute = PopulaireRouteImport.update({
  id: '/populaire',
  path: '/populaire',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenaireRoute = PartenaireRouteImport.update({
  id: '/partenaire',
  path: '/partenaire',
  getParentRoute: () => rootRouteImport,
} as any)
const ParrainageRoute = ParrainageRouteImport.update({
  id: '/parrainage',
  path: '/parrainage',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const MboapassRoute = MboapassRouteImport.update({
  id: '/mboapass',
  path: '/mboapass',
  getParentRoute: () => rootRouteImport,
} as any)
const MboaAiRoute = MboaAiRouteImport.update({
  id: '/mboa-ai',
  path: '/mboa-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const LivreurRoute = LivreurRouteImport.update({
  id: '/livreur',
  path: '/livreur',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthcheckRoute = HealthcheckRouteImport.update({
  id: '/healthcheck',
  path: '/healthcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const FideliteRoute = FideliteRouteImport.update({
  id: '/fidelite',
  path: '/fidelite',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const DevenirRestoRoute = DevenirRestoRouteImport.update({
  id: '/devenir-resto',
  path: '/devenir-resto',
  getParentRoute: () => rootRouteImport,
} as any)
const DevenirLivreurRoute = DevenirLivreurRouteImport.update({
  id: '/devenir-livreur',
  path: '/devenir-livreur',
  getParentRoute: () => rootRouteImport,
} as any)
const DecouvrirRoute = DecouvrirRouteImport.update({
  id: '/decouvrir',
  path: '/decouvrir',
  getParentRoute: () => rootRouteImport,
} as any)
const CuisinesRoute = CuisinesRouteImport.update({
  id: '/cuisines',
  path: '/cuisines',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesRoute = CommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const AideRoute = AideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => rootRouteImport,
} as any)
const AdressesRoute = AdressesRouteImport.update({
  id: '/adresses',
  path: '/adresses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRoute,
} as any)
const PartenaireIndexRoute = PartenaireIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartenaireRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TableePaiementRoute = TableePaiementRouteImport.update({
  id: '/paiement',
  path: '/paiement',
  getParentRoute: () => TableeRoute,
} as any)
const SuperadminSetup2faRoute = SuperadminSetup2faRouteImport.update({
  id: '/superadmin_/setup-2fa',
  path: '/superadmin/setup-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminLoginRoute = SuperadminLoginRouteImport.update({
  id: '/superadmin_/login',
  path: '/superadmin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRestaurantsRoute = SuperadminRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminLivreursRoute = SuperadminLivreursRouteImport.update({
  id: '/livreurs',
  path: '/livreurs',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuiviOrderIdRoute = SuiviOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => SuiviRoute,
} as any)
const RestaurantsRestoIdRoute = RestaurantsRestoIdRouteImport.update({
  id: '/restaurants/$restoId',
  path: '/restaurants/$restoId',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantConnexionRoute = RestaurantConnexionRouteImport.update({
  id: '/restaurant_/connexion',
  path: '/restaurant/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenaireRevenusRoute = PartenaireRevenusRouteImport.update({
  id: '/revenus',
  path: '/revenus',
  getParentRoute: () => PartenaireRoute,
} as any)
const PartenaireParametresRoute = PartenaireParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => PartenaireRoute,
} as any)
const PartenaireMenuRoute = PartenaireMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => PartenaireRoute,
} as any)
const PartenaireCommandesRoute = PartenaireCommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => PartenaireRoute,
} as any)
const LivreurConnexionRoute = LivreurConnexionRouteImport.update({
  id: '/livreur_/connexion',
  path: '/livreur/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteSecuriteRoute = CompteSecuriteRouteImport.update({
  id: '/compte/securite',
  path: '/compte/securite',
  getParentRoute: () => rootRouteImport,
} as any)
const ComptePaiementsRoute = ComptePaiementsRouteImport.update({
  id: '/compte/paiements',
  path: '/compte/paiements',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteLivraisonRoute = CompteLivraisonRouteImport.update({
  id: '/compte/livraison',
  path: '/compte/livraison',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteCommandesRoute = CompteCommandesRouteImport.update({
  id: '/compte/commandes',
  path: '/compte/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorieSlugRoute = CategorieSlugRouteImport.update({
  id: '/categorie/$slug',
  path: '/categorie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AideCategoryRoute = AideCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => AideRoute,
} as any)
const AdminUnauthorizedRoute = AdminUnauthorizedRouteImport.update({
  id: '/admin_/unauthorized',
  path: '/admin/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminZonesRoute = AdminZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRestaurantsRoute = AdminRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenusRoute = AdminMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLivreursRoute = AdminLivreursRouteImport.update({
  id: '/livreurs',
  path: '/livreurs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLitigesRoute = AdminLitigesRouteImport.update({
  id: '/litiges',
  path: '/litiges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommandesRoute = AdminCommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const RestaurantsRestoIdMenuRoute = RestaurantsRestoIdMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => RestaurantsRestoIdRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCampayWebhookRoute = ApiPublicCampayWebhookRouteImport.update({
  id: '/api/public/campay-webhook',
  path: '/api/public/campay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRestoIdPlatsPlatIdRoute =
  RestaurantsRestoIdPlatsPlatIdRouteImport.update({
    id: '/restaurants/$restoId_/plats/$platId',
    path: '/restaurants/$restoId/plats/$platId',
    getParentRoute: () => rootRouteImport,
  } as any)
const RSlugPlatsDishIdRoute = RSlugPlatsDishIdRouteImport.update({
  id: '/r/$slug_/plats/$dishId',
  path: '/r/$slug/plats/$dishId',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/adresses': typeof AdressesRoute
  '/aide': typeof AideRouteWithChildren
  '/cgu': typeof CguRoute
  '/checkout': typeof CheckoutRoute
  '/commandes': typeof CommandesRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/cuisines': typeof CuisinesRoute
  '/decouvrir': typeof DecouvrirRoute
  '/devenir-livreur': typeof DevenirLivreurRoute
  '/devenir-resto': typeof DevenirRestoRoute
  '/explorer': typeof ExplorerRoute
  '/favoris': typeof FavorisRoute
  '/fidelite': typeof FideliteRoute
  '/healthcheck': typeof HealthcheckRoute
  '/inscription': typeof InscriptionRoute
  '/livreur': typeof LivreurRoute
  '/mboa-ai': typeof MboaAiRoute
  '/mboapass': typeof MboapassRoute
  '/panier': typeof PanierRoute
  '/parrainage': typeof ParrainageRoute
  '/partenaire': typeof PartenaireRouteWithChildren
  '/populaire': typeof PopulaireRoute
  '/preferences': typeof PreferencesRoute
  '/profil': typeof ProfilRoute
  '/proximite': typeof ProximiteRoute
  '/recherche': typeof RechercheRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurant': typeof RestaurantRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suivi': typeof SuiviRouteWithChildren
  '/superadmin': typeof SuperadminRouteWithChildren
  '/tablee': typeof TableeRouteWithChildren
  '/admin/clients': typeof AdminClientsRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/litiges': typeof AdminLitigesRoute
  '/admin/livreurs': typeof AdminLivreursRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/menus': typeof AdminMenusRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/zones': typeof AdminZonesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/unauthorized': typeof AdminUnauthorizedRoute
  '/aide/$category': typeof AideCategoryRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/compte/commandes': typeof CompteCommandesRoute
  '/compte/livraison': typeof CompteLivraisonRoute
  '/compte/paiements': typeof ComptePaiementsRoute
  '/compte/securite': typeof CompteSecuriteRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/livreur/connexion': typeof LivreurConnexionRoute
  '/partenaire/commandes': typeof PartenaireCommandesRoute
  '/partenaire/menu': typeof PartenaireMenuRoute
  '/partenaire/parametres': typeof PartenaireParametresRoute
  '/partenaire/revenus': typeof PartenaireRevenusRoute
  '/r/$slug': typeof RSlugRoute
  '/restaurant/connexion': typeof RestaurantConnexionRoute
  '/restaurants/$restoId': typeof RestaurantsRestoIdRouteWithChildren
  '/suivi/$orderId': typeof SuiviOrderIdRoute
  '/superadmin/livreurs': typeof SuperadminLivreursRoute
  '/superadmin/restaurants': typeof SuperadminRestaurantsRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/superadmin/setup-2fa': typeof SuperadminSetup2faRoute
  '/tablee/paiement': typeof TableePaiementRoute
  '/admin/': typeof AdminIndexRoute
  '/partenaire/': typeof PartenaireIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/api/public/campay-webhook': typeof ApiPublicCampayWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/restaurants/$restoId/menu': typeof RestaurantsRestoIdMenuRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/r/$slug/plats/$dishId': typeof RSlugPlatsDishIdRoute
  '/restaurants/$restoId/plats/$platId': typeof RestaurantsRestoIdPlatsPlatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adresses': typeof AdressesRoute
  '/aide': typeof AideRouteWithChildren
  '/cgu': typeof CguRoute
  '/checkout': typeof CheckoutRoute
  '/commandes': typeof CommandesRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/cuisines': typeof CuisinesRoute
  '/decouvrir': typeof DecouvrirRoute
  '/devenir-livreur': typeof DevenirLivreurRoute
  '/devenir-resto': typeof DevenirRestoRoute
  '/explorer': typeof ExplorerRoute
  '/favoris': typeof FavorisRoute
  '/fidelite': typeof FideliteRoute
  '/healthcheck': typeof HealthcheckRoute
  '/inscription': typeof InscriptionRoute
  '/livreur': typeof LivreurRoute
  '/mboa-ai': typeof MboaAiRoute
  '/mboapass': typeof MboapassRoute
  '/panier': typeof PanierRoute
  '/parrainage': typeof ParrainageRoute
  '/populaire': typeof PopulaireRoute
  '/preferences': typeof PreferencesRoute
  '/profil': typeof ProfilRoute
  '/proximite': typeof ProximiteRoute
  '/recherche': typeof RechercheRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurant': typeof RestaurantRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suivi': typeof SuiviRouteWithChildren
  '/tablee': typeof TableeRouteWithChildren
  '/admin/clients': typeof AdminClientsRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/litiges': typeof AdminLitigesRoute
  '/admin/livreurs': typeof AdminLivreursRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/menus': typeof AdminMenusRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/zones': typeof AdminZonesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/unauthorized': typeof AdminUnauthorizedRoute
  '/aide/$category': typeof AideCategoryRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/compte/commandes': typeof CompteCommandesRoute
  '/compte/livraison': typeof CompteLivraisonRoute
  '/compte/paiements': typeof ComptePaiementsRoute
  '/compte/securite': typeof CompteSecuriteRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/livreur/connexion': typeof LivreurConnexionRoute
  '/partenaire/commandes': typeof PartenaireCommandesRoute
  '/partenaire/menu': typeof PartenaireMenuRoute
  '/partenaire/parametres': typeof PartenaireParametresRoute
  '/partenaire/revenus': typeof PartenaireRevenusRoute
  '/r/$slug': typeof RSlugRoute
  '/restaurant/connexion': typeof RestaurantConnexionRoute
  '/restaurants/$restoId': typeof RestaurantsRestoIdRouteWithChildren
  '/suivi/$orderId': typeof SuiviOrderIdRoute
  '/superadmin/livreurs': typeof SuperadminLivreursRoute
  '/superadmin/restaurants': typeof SuperadminRestaurantsRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/superadmin/setup-2fa': typeof SuperadminSetup2faRoute
  '/tablee/paiement': typeof TableePaiementRoute
  '/admin': typeof AdminIndexRoute
  '/partenaire': typeof PartenaireIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/api/public/campay-webhook': typeof ApiPublicCampayWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/restaurants/$restoId/menu': typeof RestaurantsRestoIdMenuRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/r/$slug/plats/$dishId': typeof RSlugPlatsDishIdRoute
  '/restaurants/$restoId/plats/$platId': typeof RestaurantsRestoIdPlatsPlatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/adresses': typeof AdressesRoute
  '/aide': typeof AideRouteWithChildren
  '/cgu': typeof CguRoute
  '/checkout': typeof CheckoutRoute
  '/commandes': typeof CommandesRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/cuisines': typeof CuisinesRoute
  '/decouvrir': typeof DecouvrirRoute
  '/devenir-livreur': typeof DevenirLivreurRoute
  '/devenir-resto': typeof DevenirRestoRoute
  '/explorer': typeof ExplorerRoute
  '/favoris': typeof FavorisRoute
  '/fidelite': typeof FideliteRoute
  '/healthcheck': typeof HealthcheckRoute
  '/inscription': typeof InscriptionRoute
  '/livreur': typeof LivreurRoute
  '/mboa-ai': typeof MboaAiRoute
  '/mboapass': typeof MboapassRoute
  '/panier': typeof PanierRoute
  '/parrainage': typeof ParrainageRoute
  '/partenaire': typeof PartenaireRouteWithChildren
  '/populaire': typeof PopulaireRoute
  '/preferences': typeof PreferencesRoute
  '/profil': typeof ProfilRoute
  '/proximite': typeof ProximiteRoute
  '/recherche': typeof RechercheRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurant': typeof RestaurantRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suivi': typeof SuiviRouteWithChildren
  '/superadmin': typeof SuperadminRouteWithChildren
  '/tablee': typeof TableeRouteWithChildren
  '/admin/clients': typeof AdminClientsRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/litiges': typeof AdminLitigesRoute
  '/admin/livreurs': typeof AdminLivreursRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/menus': typeof AdminMenusRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/zones': typeof AdminZonesRoute
  '/admin_/login': typeof AdminLoginRoute
  '/admin_/unauthorized': typeof AdminUnauthorizedRoute
  '/aide/$category': typeof AideCategoryRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/compte/commandes': typeof CompteCommandesRoute
  '/compte/livraison': typeof CompteLivraisonRoute
  '/compte/paiements': typeof ComptePaiementsRoute
  '/compte/securite': typeof CompteSecuriteRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/livreur_/connexion': typeof LivreurConnexionRoute
  '/partenaire/commandes': typeof PartenaireCommandesRoute
  '/partenaire/menu': typeof PartenaireMenuRoute
  '/partenaire/parametres': typeof PartenaireParametresRoute
  '/partenaire/revenus': typeof PartenaireRevenusRoute
  '/r/$slug': typeof RSlugRoute
  '/restaurant_/connexion': typeof RestaurantConnexionRoute
  '/restaurants/$restoId': typeof RestaurantsRestoIdRouteWithChildren
  '/suivi/$orderId': typeof SuiviOrderIdRoute
  '/superadmin/livreurs': typeof SuperadminLivreursRoute
  '/superadmin/restaurants': typeof SuperadminRestaurantsRoute
  '/superadmin_/login': typeof SuperadminLoginRoute
  '/superadmin_/setup-2fa': typeof SuperadminSetup2faRoute
  '/tablee/paiement': typeof TableePaiementRoute
  '/admin/': typeof AdminIndexRoute
  '/partenaire/': typeof PartenaireIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/api/public/campay-webhook': typeof ApiPublicCampayWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/restaurants/$restoId/menu': typeof RestaurantsRestoIdMenuRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/r/$slug_/plats/$dishId': typeof RSlugPlatsDishIdRoute
  '/restaurants/$restoId_/plats/$platId': typeof RestaurantsRestoIdPlatsPlatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/adresses'
    | '/aide'
    | '/cgu'
    | '/checkout'
    | '/commandes'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/cuisines'
    | '/decouvrir'
    | '/devenir-livreur'
    | '/devenir-resto'
    | '/explorer'
    | '/favoris'
    | '/fidelite'
    | '/healthcheck'
    | '/inscription'
    | '/livreur'
    | '/mboa-ai'
    | '/mboapass'
    | '/panier'
    | '/parrainage'
    | '/partenaire'
    | '/populaire'
    | '/preferences'
    | '/profil'
    | '/proximite'
    | '/recherche'
    | '/reset-password'
    | '/restaurant'
    | '/sitemap.xml'
    | '/suivi'
    | '/superadmin'
    | '/tablee'
    | '/admin/clients'
    | '/admin/commandes'
    | '/admin/commissions'
    | '/admin/litiges'
    | '/admin/livreurs'
    | '/admin/logs'
    | '/admin/menus'
    | '/admin/parametres'
    | '/admin/restaurants'
    | '/admin/zones'
    | '/admin/login'
    | '/admin/unauthorized'
    | '/aide/$category'
    | '/categorie/$slug'
    | '/compte/commandes'
    | '/compte/livraison'
    | '/compte/paiements'
    | '/compte/securite'
    | '/email/unsubscribe'
    | '/livreur/connexion'
    | '/partenaire/commandes'
    | '/partenaire/menu'
    | '/partenaire/parametres'
    | '/partenaire/revenus'
    | '/r/$slug'
    | '/restaurant/connexion'
    | '/restaurants/$restoId'
    | '/suivi/$orderId'
    | '/superadmin/livreurs'
    | '/superadmin/restaurants'
    | '/superadmin/login'
    | '/superadmin/setup-2fa'
    | '/tablee/paiement'
    | '/admin/'
    | '/partenaire/'
    | '/superadmin/'
    | '/api/public/campay-webhook'
    | '/lovable/email/suppression'
    | '/restaurants/$restoId/menu'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/r/$slug/plats/$dishId'
    | '/restaurants/$restoId/plats/$platId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adresses'
    | '/aide'
    | '/cgu'
    | '/checkout'
    | '/commandes'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/cuisines'
    | '/decouvrir'
    | '/devenir-livreur'
    | '/devenir-resto'
    | '/explorer'
    | '/favoris'
    | '/fidelite'
    | '/healthcheck'
    | '/inscription'
    | '/livreur'
    | '/mboa-ai'
    | '/mboapass'
    | '/panier'
    | '/parrainage'
    | '/populaire'
    | '/preferences'
    | '/profil'
    | '/proximite'
    | '/recherche'
    | '/reset-password'
    | '/restaurant'
    | '/sitemap.xml'
    | '/suivi'
    | '/tablee'
    | '/admin/clients'
    | '/admin/commandes'
    | '/admin/commissions'
    | '/admin/litiges'
    | '/admin/livreurs'
    | '/admin/logs'
    | '/admin/menus'
    | '/admin/parametres'
    | '/admin/restaurants'
    | '/admin/zones'
    | '/admin/login'
    | '/admin/unauthorized'
    | '/aide/$category'
    | '/categorie/$slug'
    | '/compte/commandes'
    | '/compte/livraison'
    | '/compte/paiements'
    | '/compte/securite'
    | '/email/unsubscribe'
    | '/livreur/connexion'
    | '/partenaire/commandes'
    | '/partenaire/menu'
    | '/partenaire/parametres'
    | '/partenaire/revenus'
    | '/r/$slug'
    | '/restaurant/connexion'
    | '/restaurants/$restoId'
    | '/suivi/$orderId'
    | '/superadmin/livreurs'
    | '/superadmin/restaurants'
    | '/superadmin/login'
    | '/superadmin/setup-2fa'
    | '/tablee/paiement'
    | '/admin'
    | '/partenaire'
    | '/superadmin'
    | '/api/public/campay-webhook'
    | '/lovable/email/suppression'
    | '/restaurants/$restoId/menu'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/r/$slug/plats/$dishId'
    | '/restaurants/$restoId/plats/$platId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/adresses'
    | '/aide'
    | '/cgu'
    | '/checkout'
    | '/commandes'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/cuisines'
    | '/decouvrir'
    | '/devenir-livreur'
    | '/devenir-resto'
    | '/explorer'
    | '/favoris'
    | '/fidelite'
    | '/healthcheck'
    | '/inscription'
    | '/livreur'
    | '/mboa-ai'
    | '/mboapass'
    | '/panier'
    | '/parrainage'
    | '/partenaire'
    | '/populaire'
    | '/preferences'
    | '/profil'
    | '/proximite'
    | '/recherche'
    | '/reset-password'
    | '/restaurant'
    | '/sitemap.xml'
    | '/suivi'
    | '/superadmin'
    | '/tablee'
    | '/admin/clients'
    | '/admin/commandes'
    | '/admin/commissions'
    | '/admin/litiges'
    | '/admin/livreurs'
    | '/admin/logs'
    | '/admin/menus'
    | '/admin/parametres'
    | '/admin/restaurants'
    | '/admin/zones'
    | '/admin_/login'
    | '/admin_/unauthorized'
    | '/aide/$category'
    | '/categorie/$slug'
    | '/compte/commandes'
    | '/compte/livraison'
    | '/compte/paiements'
    | '/compte/securite'
    | '/email/unsubscribe'
    | '/livreur_/connexion'
    | '/partenaire/commandes'
    | '/partenaire/menu'
    | '/partenaire/parametres'
    | '/partenaire/revenus'
    | '/r/$slug'
    | '/restaurant_/connexion'
    | '/restaurants/$restoId'
    | '/suivi/$orderId'
    | '/superadmin/livreurs'
    | '/superadmin/restaurants'
    | '/superadmin_/login'
    | '/superadmin_/setup-2fa'
    | '/tablee/paiement'
    | '/admin/'
    | '/partenaire/'
    | '/superadmin/'
    | '/api/public/campay-webhook'
    | '/lovable/email/suppression'
    | '/restaurants/$restoId/menu'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/r/$slug_/plats/$dishId'
    | '/restaurants/$restoId_/plats/$platId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdressesRoute: typeof AdressesRoute
  AideRoute: typeof AideRouteWithChildren
  CguRoute: typeof CguRoute
  CheckoutRoute: typeof CheckoutRoute
  CommandesRoute: typeof CommandesRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConnexionRoute: typeof ConnexionRoute
  ContactRoute: typeof ContactRoute
  CuisinesRoute: typeof CuisinesRoute
  DecouvrirRoute: typeof DecouvrirRoute
  DevenirLivreurRoute: typeof DevenirLivreurRoute
  DevenirRestoRoute: typeof DevenirRestoRoute
  ExplorerRoute: typeof ExplorerRoute
  FavorisRoute: typeof FavorisRoute
  FideliteRoute: typeof FideliteRoute
  HealthcheckRoute: typeof HealthcheckRoute
  InscriptionRoute: typeof InscriptionRoute
  LivreurRoute: typeof LivreurRoute
  MboaAiRoute: typeof MboaAiRoute
  MboapassRoute: typeof MboapassRoute
  PanierRoute: typeof PanierRoute
  ParrainageRoute: typeof ParrainageRoute
  PartenaireRoute: typeof PartenaireRouteWithChildren
  PopulaireRoute: typeof PopulaireRoute
  PreferencesRoute: typeof PreferencesRoute
  ProfilRoute: typeof ProfilRoute
  ProximiteRoute: typeof ProximiteRoute
  RechercheRoute: typeof RechercheRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RestaurantRoute: typeof RestaurantRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuiviRoute: typeof SuiviRouteWithChildren
  SuperadminRoute: typeof SuperadminRouteWithChildren
  TableeRoute: typeof TableeRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminUnauthorizedRoute: typeof AdminUnauthorizedRoute
  CategorieSlugRoute: typeof CategorieSlugRoute
  CompteCommandesRoute: typeof CompteCommandesRoute
  CompteLivraisonRoute: typeof CompteLivraisonRoute
  ComptePaiementsRoute: typeof ComptePaiementsRoute
  CompteSecuriteRoute: typeof CompteSecuriteRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LivreurConnexionRoute: typeof LivreurConnexionRoute
  RSlugRoute: typeof RSlugRoute
  RestaurantConnexionRoute: typeof RestaurantConnexionRoute
  RestaurantsRestoIdRoute: typeof RestaurantsRestoIdRouteWithChildren
  SuperadminLoginRoute: typeof SuperadminLoginRoute
  SuperadminSetup2faRoute: typeof SuperadminSetup2faRoute
  ApiPublicCampayWebhookRoute: typeof ApiPublicCampayWebhookRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
  RSlugPlatsDishIdRoute: typeof RSlugPlatsDishIdRoute
  RestaurantsRestoIdPlatsPlatIdRoute: typeof RestaurantsRestoIdPlatsPlatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tablee': {
      id: '/tablee'
      path: '/tablee'
      fullPath: '/tablee'
      preLoaderRoute: typeof TableeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi': {
      id: '/suivi'
      path: '/suivi'
      fullPath: '/suivi'
      preLoaderRoute: typeof SuiviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proximite': {
      id: '/proximite'
      path: '/proximite'
      fullPath: '/proximite'
      preLoaderRoute: typeof ProximiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/populaire': {
      id: '/populaire'
      path: '/populaire'
      fullPath: '/populaire'
      preLoaderRoute: typeof PopulaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaire': {
      id: '/partenaire'
      path: '/partenaire'
      fullPath: '/partenaire'
      preLoaderRoute: typeof PartenaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parrainage': {
      id: '/parrainage'
      path: '/parrainage'
      fullPath: '/parrainage'
      preLoaderRoute: typeof ParrainageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mboapass': {
      id: '/mboapass'
      path: '/mboapass'
      fullPath: '/mboapass'
      preLoaderRoute: typeof MboapassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mboa-ai': {
      id: '/mboa-ai'
      path: '/mboa-ai'
      fullPath: '/mboa-ai'
      preLoaderRoute: typeof MboaAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livreur': {
      id: '/livreur'
      path: '/livreur'
      fullPath: '/livreur'
      preLoaderRoute: typeof LivreurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthcheck': {
      id: '/healthcheck'
      path: '/healthcheck'
      fullPath: '/healthcheck'
      preLoaderRoute: typeof HealthcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fidelite': {
      id: '/fidelite'
      path: '/fidelite'
      fullPath: '/fidelite'
      preLoaderRoute: typeof FideliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris': {
      id: '/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof FavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devenir-resto': {
      id: '/devenir-resto'
      path: '/devenir-resto'
      fullPath: '/devenir-resto'
      preLoaderRoute: typeof DevenirRestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devenir-livreur': {
      id: '/devenir-livreur'
      path: '/devenir-livreur'
      fullPath: '/devenir-livreur'
      preLoaderRoute: typeof DevenirLivreurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decouvrir': {
      id: '/decouvrir'
      path: '/decouvrir'
      fullPath: '/decouvrir'
      preLoaderRoute: typeof DecouvrirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuisines': {
      id: '/cuisines'
      path: '/cuisines'
      fullPath: '/cuisines'
      preLoaderRoute: typeof CuisinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes': {
      id: '/commandes'
      path: '/commandes'
      fullPath: '/commandes'
      preLoaderRoute: typeof CommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide': {
      id: '/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adresses': {
      id: '/adresses'
      path: '/adresses'
      fullPath: '/adresses'
      preLoaderRoute: typeof AdressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/partenaire/': {
      id: '/partenaire/'
      path: '/'
      fullPath: '/partenaire/'
      preLoaderRoute: typeof PartenaireIndexRouteImport
      parentRoute: typeof PartenaireRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tablee/paiement': {
      id: '/tablee/paiement'
      path: '/paiement'
      fullPath: '/tablee/paiement'
      preLoaderRoute: typeof TableePaiementRouteImport
      parentRoute: typeof TableeRoute
    }
    '/superadmin_/setup-2fa': {
      id: '/superadmin_/setup-2fa'
      path: '/superadmin/setup-2fa'
      fullPath: '/superadmin/setup-2fa'
      preLoaderRoute: typeof SuperadminSetup2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin_/login': {
      id: '/superadmin_/login'
      path: '/superadmin/login'
      fullPath: '/superadmin/login'
      preLoaderRoute: typeof SuperadminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/restaurants': {
      id: '/superadmin/restaurants'
      path: '/restaurants'
      fullPath: '/superadmin/restaurants'
      preLoaderRoute: typeof SuperadminRestaurantsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/livreurs': {
      id: '/superadmin/livreurs'
      path: '/livreurs'
      fullPath: '/superadmin/livreurs'
      preLoaderRoute: typeof SuperadminLivreursRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/suivi/$orderId': {
      id: '/suivi/$orderId'
      path: '/$orderId'
      fullPath: '/suivi/$orderId'
      preLoaderRoute: typeof SuiviOrderIdRouteImport
      parentRoute: typeof SuiviRoute
    }
    '/restaurants/$restoId': {
      id: '/restaurants/$restoId'
      path: '/restaurants/$restoId'
      fullPath: '/restaurants/$restoId'
      preLoaderRoute: typeof RestaurantsRestoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant_/connexion': {
      id: '/restaurant_/connexion'
      path: '/restaurant/connexion'
      fullPath: '/restaurant/connexion'
      preLoaderRoute: typeof RestaurantConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaire/revenus': {
      id: '/partenaire/revenus'
      path: '/revenus'
      fullPath: '/partenaire/revenus'
      preLoaderRoute: typeof PartenaireRevenusRouteImport
      parentRoute: typeof PartenaireRoute
    }
    '/partenaire/parametres': {
      id: '/partenaire/parametres'
      path: '/parametres'
      fullPath: '/partenaire/parametres'
      preLoaderRoute: typeof PartenaireParametresRouteImport
      parentRoute: typeof PartenaireRoute
    }
    '/partenaire/menu': {
      id: '/partenaire/menu'
      path: '/menu'
      fullPath: '/partenaire/menu'
      preLoaderRoute: typeof PartenaireMenuRouteImport
      parentRoute: typeof PartenaireRoute
    }
    '/partenaire/commandes': {
      id: '/partenaire/commandes'
      path: '/commandes'
      fullPath: '/partenaire/commandes'
      preLoaderRoute: typeof PartenaireCommandesRouteImport
      parentRoute: typeof PartenaireRoute
    }
    '/livreur_/connexion': {
      id: '/livreur_/connexion'
      path: '/livreur/connexion'
      fullPath: '/livreur/connexion'
      preLoaderRoute: typeof LivreurConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/securite': {
      id: '/compte/securite'
      path: '/compte/securite'
      fullPath: '/compte/securite'
      preLoaderRoute: typeof CompteSecuriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/paiements': {
      id: '/compte/paiements'
      path: '/compte/paiements'
      fullPath: '/compte/paiements'
      preLoaderRoute: typeof ComptePaiementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/livraison': {
      id: '/compte/livraison'
      path: '/compte/livraison'
      fullPath: '/compte/livraison'
      preLoaderRoute: typeof CompteLivraisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/commandes': {
      id: '/compte/commandes'
      path: '/compte/commandes'
      fullPath: '/compte/commandes'
      preLoaderRoute: typeof CompteCommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorie/$slug': {
      id: '/categorie/$slug'
      path: '/categorie/$slug'
      fullPath: '/categorie/$slug'
      preLoaderRoute: typeof CategorieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide/$category': {
      id: '/aide/$category'
      path: '/$category'
      fullPath: '/aide/$category'
      preLoaderRoute: typeof AideCategoryRouteImport
      parentRoute: typeof AideRoute
    }
    '/admin_/unauthorized': {
      id: '/admin_/unauthorized'
      path: '/admin/unauthorized'
      fullPath: '/admin/unauthorized'
      preLoaderRoute: typeof AdminUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/zones': {
      id: '/admin/zones'
      path: '/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AdminZonesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/restaurants': {
      id: '/admin/restaurants'
      path: '/restaurants'
      fullPath: '/admin/restaurants'
      preLoaderRoute: typeof AdminRestaurantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menus': {
      id: '/admin/menus'
      path: '/menus'
      fullPath: '/admin/menus'
      preLoaderRoute: typeof AdminMenusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/livreurs': {
      id: '/admin/livreurs'
      path: '/livreurs'
      fullPath: '/admin/livreurs'
      preLoaderRoute: typeof AdminLivreursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/litiges': {
      id: '/admin/litiges'
      path: '/litiges'
      fullPath: '/admin/litiges'
      preLoaderRoute: typeof AdminLitigesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commandes': {
      id: '/admin/commandes'
      path: '/commandes'
      fullPath: '/admin/commandes'
      preLoaderRoute: typeof AdminCommandesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/restaurants/$restoId/menu': {
      id: '/restaurants/$restoId/menu'
      path: '/menu'
      fullPath: '/restaurants/$restoId/menu'
      preLoaderRoute: typeof RestaurantsRestoIdMenuRouteImport
      parentRoute: typeof RestaurantsRestoIdRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/campay-webhook': {
      id: '/api/public/campay-webhook'
      path: '/api/public/campay-webhook'
      fullPath: '/api/public/campay-webhook'
      preLoaderRoute: typeof ApiPublicCampayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$restoId_/plats/$platId': {
      id: '/restaurants/$restoId_/plats/$platId'
      path: '/restaurants/$restoId/plats/$platId'
      fullPath: '/restaurants/$restoId/plats/$platId'
      preLoaderRoute: typeof RestaurantsRestoIdPlatsPlatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug_/plats/$dishId': {
      id: '/r/$slug_/plats/$dishId'
      path: '/r/$slug/plats/$dishId'
      fullPath: '/r/$slug/plats/$dishId'
      preLoaderRoute: typeof RSlugPlatsDishIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminClientsRoute: typeof AdminClientsRoute
  AdminCommandesRoute: typeof AdminCommandesRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminLitigesRoute: typeof AdminLitigesRoute
  AdminLivreursRoute: typeof AdminLivreursRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMenusRoute: typeof AdminMenusRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminRestaurantsRoute: typeof AdminRestaurantsRoute
  AdminZonesRoute: typeof AdminZonesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientsRoute: AdminClientsRoute,
  AdminCommandesRoute: AdminCommandesRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminLitigesRoute: AdminLitigesRoute,
  AdminLivreursRoute: AdminLivreursRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMenusRoute: AdminMenusRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminRestaurantsRoute: AdminRestaurantsRoute,
  AdminZonesRoute: AdminZonesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AideRouteChildren {
  AideCategoryRoute: typeof AideCategoryRoute
}

const AideRouteChildren: AideRouteChildren = {
  AideCategoryRoute: AideCategoryRoute,
}

const AideRouteWithChildren = AideRoute._addFileChildren(AideRouteChildren)

interface PartenaireRouteChildren {
  PartenaireCommandesRoute: typeof PartenaireCommandesRoute
  PartenaireMenuRoute: typeof PartenaireMenuRoute
  PartenaireParametresRoute: typeof PartenaireParametresRoute
  PartenaireRevenusRoute: typeof PartenaireRevenusRoute
  PartenaireIndexRoute: typeof PartenaireIndexRoute
}

const PartenaireRouteChildren: PartenaireRouteChildren = {
  PartenaireCommandesRoute: PartenaireCommandesRoute,
  PartenaireMenuRoute: PartenaireMenuRoute,
  PartenaireParametresRoute: PartenaireParametresRoute,
  PartenaireRevenusRoute: PartenaireRevenusRoute,
  PartenaireIndexRoute: PartenaireIndexRoute,
}

const PartenaireRouteWithChildren = PartenaireRoute._addFileChildren(
  PartenaireRouteChildren,
)

interface SuiviRouteChildren {
  SuiviOrderIdRoute: typeof SuiviOrderIdRoute
}

const SuiviRouteChildren: SuiviRouteChildren = {
  SuiviOrderIdRoute: SuiviOrderIdRoute,
}

const SuiviRouteWithChildren = SuiviRoute._addFileChildren(SuiviRouteChildren)

interface SuperadminRouteChildren {
  SuperadminLivreursRoute: typeof SuperadminLivreursRoute
  SuperadminRestaurantsRoute: typeof SuperadminRestaurantsRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminLivreursRoute: SuperadminLivreursRoute,
  SuperadminRestaurantsRoute: SuperadminRestaurantsRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

interface TableeRouteChildren {
  TableePaiementRoute: typeof TableePaiementRoute
}

const TableeRouteChildren: TableeRouteChildren = {
  TableePaiementRoute: TableePaiementRoute,
}

const TableeRouteWithChildren =
  TableeRoute._addFileChildren(TableeRouteChildren)

interface RestaurantsRestoIdRouteChildren {
  RestaurantsRestoIdMenuRoute: typeof RestaurantsRestoIdMenuRoute
}

const RestaurantsRestoIdRouteChildren: RestaurantsRestoIdRouteChildren = {
  RestaurantsRestoIdMenuRoute: RestaurantsRestoIdMenuRoute,
}

const RestaurantsRestoIdRouteWithChildren =
  RestaurantsRestoIdRoute._addFileChildren(RestaurantsRestoIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdressesRoute: AdressesRoute,
  AideRoute: AideRouteWithChildren,
  CguRoute: CguRoute,
  CheckoutRoute: CheckoutRoute,
  CommandesRoute: CommandesRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConnexionRoute: ConnexionRoute,
  ContactRoute: ContactRoute,
  CuisinesRoute: CuisinesRoute,
  DecouvrirRoute: DecouvrirRoute,
  DevenirLivreurRoute: DevenirLivreurRoute,
  DevenirRestoRoute: DevenirRestoRoute,
  ExplorerRoute: ExplorerRoute,
  FavorisRoute: FavorisRoute,
  FideliteRoute: FideliteRoute,
  HealthcheckRoute: HealthcheckRoute,
  InscriptionRoute: InscriptionRoute,
  LivreurRoute: LivreurRoute,
  MboaAiRoute: MboaAiRoute,
  MboapassRoute: MboapassRoute,
  PanierRoute: PanierRoute,
  ParrainageRoute: ParrainageRoute,
  PartenaireRoute: PartenaireRouteWithChildren,
  PopulaireRoute: PopulaireRoute,
  PreferencesRoute: PreferencesRoute,
  ProfilRoute: ProfilRoute,
  ProximiteRoute: ProximiteRoute,
  RechercheRoute: RechercheRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RestaurantRoute: RestaurantRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuiviRoute: SuiviRouteWithChildren,
  SuperadminRoute: SuperadminRouteWithChildren,
  TableeRoute: TableeRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminUnauthorizedRoute: AdminUnauthorizedRoute,
  CategorieSlugRoute: CategorieSlugRoute,
  CompteCommandesRoute: CompteCommandesRoute,
  CompteLivraisonRoute: CompteLivraisonRoute,
  ComptePaiementsRoute: ComptePaiementsRoute,
  CompteSecuriteRoute: CompteSecuriteRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LivreurConnexionRoute: LivreurConnexionRoute,
  RSlugRoute: RSlugRoute,
  RestaurantConnexionRoute: RestaurantConnexionRoute,
  RestaurantsRestoIdRoute: RestaurantsRestoIdRouteWithChildren,
  SuperadminLoginRoute: SuperadminLoginRoute,
  SuperadminSetup2faRoute: SuperadminSetup2faRoute,
  ApiPublicCampayWebhookRoute: ApiPublicCampayWebhookRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
  RSlugPlatsDishIdRoute: RSlugPlatsDishIdRoute,
  RestaurantsRestoIdPlatsPlatIdRoute: RestaurantsRestoIdPlatsPlatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
