/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TableeRouteImport } from './routes/tablee'
import { Route as SuiviRouteImport } from './routes/suivi'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ParrainageRouteImport } from './routes/parrainage'
import { Route as MboapassRouteImport } from './routes/mboapass'
import { Route as MboaAiRouteImport } from './routes/mboa-ai'
import { Route as LivreurRouteImport } from './routes/livreur'
import { Route as FideliteRouteImport } from './routes/fidelite'
import { Route as DevenirRestoRouteImport } from './routes/devenir-resto'
import { Route as DevenirLivreurRouteImport } from './routes/devenir-livreur'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CommandesRouteImport } from './routes/commandes'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AideRouteImport } from './routes/aide'
import { Route as AdressesRouteImport } from './routes/adresses'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TableePaiementRouteImport } from './routes/tablee.paiement'
import { Route as SuiviOrderIdRouteImport } from './routes/suivi.$orderId'
import { Route as RestaurantsRestoIdRouteImport } from './routes/restaurants.$restoId'
import { Route as CategorieSlugRouteImport } from './routes/categorie.$slug'
import { Route as AdminZonesRouteImport } from './routes/admin.zones'
import { Route as AdminRestaurantsRouteImport } from './routes/admin.restaurants'
import { Route as AdminLivreursRouteImport } from './routes/admin.livreurs'
import { Route as AdminLitigesRouteImport } from './routes/admin.litiges'
import { Route as AdminCommissionsRouteImport } from './routes/admin.commissions'
import { Route as RestaurantsRestoIdPlatsPlatIdRouteImport } from './routes/restaurants.$restoId.plats.$platId'

const TableeRoute = TableeRouteImport.update({
  id: '/tablee',
  path: '/tablee',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviRoute = SuiviRouteImport.update({
  id: '/suivi',
  path: '/suivi',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ParrainageRoute = ParrainageRouteImport.update({
  id: '/parrainage',
  path: '/parrainage',
  getParentRoute: () => rootRouteImport,
} as any)
const MboapassRoute = MboapassRouteImport.update({
  id: '/mboapass',
  path: '/mboapass',
  getParentRoute: () => rootRouteImport,
} as any)
const MboaAiRoute = MboaAiRouteImport.update({
  id: '/mboa-ai',
  path: '/mboa-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const LivreurRoute = LivreurRouteImport.update({
  id: '/livreur',
  path: '/livreur',
  getParentRoute: () => rootRouteImport,
} as any)
const FideliteRoute = FideliteRouteImport.update({
  id: '/fidelite',
  path: '/fidelite',
  getParentRoute: () => rootRouteImport,
} as any)
const DevenirRestoRoute = DevenirRestoRouteImport.update({
  id: '/devenir-resto',
  path: '/devenir-resto',
  getParentRoute: () => rootRouteImport,
} as any)
const DevenirLivreurRoute = DevenirLivreurRouteImport.update({
  id: '/devenir-livreur',
  path: '/devenir-livreur',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesRoute = CommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AideRoute = AideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => rootRouteImport,
} as any)
const AdressesRoute = AdressesRouteImport.update({
  id: '/adresses',
  path: '/adresses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TableePaiementRoute = TableePaiementRouteImport.update({
  id: '/paiement',
  path: '/paiement',
  getParentRoute: () => TableeRoute,
} as any)
const SuiviOrderIdRoute = SuiviOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => SuiviRoute,
} as any)
const RestaurantsRestoIdRoute = RestaurantsRestoIdRouteImport.update({
  id: '/restaurants/$restoId',
  path: '/restaurants/$restoId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorieSlugRoute = CategorieSlugRouteImport.update({
  id: '/categorie/$slug',
  path: '/categorie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminZonesRoute = AdminZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRestaurantsRoute = AdminRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLivreursRoute = AdminLivreursRouteImport.update({
  id: '/livreurs',
  path: '/livreurs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLitigesRoute = AdminLitigesRouteImport.update({
  id: '/litiges',
  path: '/litiges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AdminRoute,
} as any)
const RestaurantsRestoIdPlatsPlatIdRoute =
  RestaurantsRestoIdPlatsPlatIdRouteImport.update({
    id: '/plats/$platId',
    path: '/plats/$platId',
    getParentRoute: () => RestaurantsRestoIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/adresses': typeof AdressesRoute
  '/aide': typeof AideRoute
  '/checkout': typeof CheckoutRoute
  '/commandes': typeof CommandesRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/devenir-livreur': typeof DevenirLivreurRoute
  '/devenir-resto': typeof DevenirRestoRoute
  '/fidelite': typeof FideliteRoute
  '/livreur': typeof LivreurRoute
  '/mboa-ai': typeof MboaAiRoute
  '/mboapass': typeof MboapassRoute
  '/parrainage': typeof ParrainageRoute
  '/profil': typeof ProfilRoute
  '/recherche': typeof RechercheRoute
  '/restaurant': typeof RestaurantRoute
  '/suivi': typeof SuiviRouteWithChildren
  '/tablee': typeof TableeRouteWithChildren
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/litiges': typeof AdminLitigesRoute
  '/admin/livreurs': typeof AdminLivreursRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/zones': typeof AdminZonesRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/restaurants/$restoId': typeof RestaurantsRestoIdRouteWithChildren
  '/suivi/$orderId': typeof SuiviOrderIdRoute
  '/tablee/paiement': typeof TableePaiementRoute
  '/admin/': typeof AdminIndexRoute
  '/restaurants/$restoId/plats/$platId': typeof RestaurantsRestoIdPlatsPlatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/adresses': typeof AdressesRoute
  '/aide': typeof AideRoute
  '/checkout': typeof CheckoutRoute
  '/commandes': typeof CommandesRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/devenir-livreur': typeof DevenirLivreurRoute
  '/devenir-resto': typeof DevenirRestoRoute
  '/fidelite': typeof FideliteRoute
  '/livreur': typeof LivreurRoute
  '/mboa-ai': typeof MboaAiRoute
  '/mboapass': typeof MboapassRoute
  '/parrainage': typeof ParrainageRoute
  '/profil': typeof ProfilRoute
  '/recherche': typeof RechercheRoute
  '/restaurant': typeof RestaurantRoute
  '/suivi': typeof SuiviRouteWithChildren
  '/tablee': typeof TableeRouteWithChildren
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/litiges': typeof AdminLitigesRoute
  '/admin/livreurs': typeof AdminLivreursRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/zones': typeof AdminZonesRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/restaurants/$restoId': typeof RestaurantsRestoIdRouteWithChildren
  '/suivi/$orderId': typeof SuiviOrderIdRoute
  '/tablee/paiement': typeof TableePaiementRoute
  '/admin': typeof AdminIndexRoute
  '/restaurants/$restoId/plats/$platId': typeof RestaurantsRestoIdPlatsPlatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/adresses': typeof AdressesRoute
  '/aide': typeof AideRoute
  '/checkout': typeof CheckoutRoute
  '/commandes': typeof CommandesRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/devenir-livreur': typeof DevenirLivreurRoute
  '/devenir-resto': typeof DevenirRestoRoute
  '/fidelite': typeof FideliteRoute
  '/livreur': typeof LivreurRoute
  '/mboa-ai': typeof MboaAiRoute
  '/mboapass': typeof MboapassRoute
  '/parrainage': typeof ParrainageRoute
  '/profil': typeof ProfilRoute
  '/recherche': typeof RechercheRoute
  '/restaurant': typeof RestaurantRoute
  '/suivi': typeof SuiviRouteWithChildren
  '/tablee': typeof TableeRouteWithChildren
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/litiges': typeof AdminLitigesRoute
  '/admin/livreurs': typeof AdminLivreursRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/zones': typeof AdminZonesRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/restaurants/$restoId': typeof RestaurantsRestoIdRouteWithChildren
  '/suivi/$orderId': typeof SuiviOrderIdRoute
  '/tablee/paiement': typeof TableePaiementRoute
  '/admin/': typeof AdminIndexRoute
  '/restaurants/$restoId/plats/$platId': typeof RestaurantsRestoIdPlatsPlatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/adresses'
    | '/aide'
    | '/checkout'
    | '/commandes'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/devenir-livreur'
    | '/devenir-resto'
    | '/fidelite'
    | '/livreur'
    | '/mboa-ai'
    | '/mboapass'
    | '/parrainage'
    | '/profil'
    | '/recherche'
    | '/restaurant'
    | '/suivi'
    | '/tablee'
    | '/admin/commissions'
    | '/admin/litiges'
    | '/admin/livreurs'
    | '/admin/restaurants'
    | '/admin/zones'
    | '/categorie/$slug'
    | '/restaurants/$restoId'
    | '/suivi/$orderId'
    | '/tablee/paiement'
    | '/admin/'
    | '/restaurants/$restoId/plats/$platId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/adresses'
    | '/aide'
    | '/checkout'
    | '/commandes'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/devenir-livreur'
    | '/devenir-resto'
    | '/fidelite'
    | '/livreur'
    | '/mboa-ai'
    | '/mboapass'
    | '/parrainage'
    | '/profil'
    | '/recherche'
    | '/restaurant'
    | '/suivi'
    | '/tablee'
    | '/admin/commissions'
    | '/admin/litiges'
    | '/admin/livreurs'
    | '/admin/restaurants'
    | '/admin/zones'
    | '/categorie/$slug'
    | '/restaurants/$restoId'
    | '/suivi/$orderId'
    | '/tablee/paiement'
    | '/admin'
    | '/restaurants/$restoId/plats/$platId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/adresses'
    | '/aide'
    | '/checkout'
    | '/commandes'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/devenir-livreur'
    | '/devenir-resto'
    | '/fidelite'
    | '/livreur'
    | '/mboa-ai'
    | '/mboapass'
    | '/parrainage'
    | '/profil'
    | '/recherche'
    | '/restaurant'
    | '/suivi'
    | '/tablee'
    | '/admin/commissions'
    | '/admin/litiges'
    | '/admin/livreurs'
    | '/admin/restaurants'
    | '/admin/zones'
    | '/categorie/$slug'
    | '/restaurants/$restoId'
    | '/suivi/$orderId'
    | '/tablee/paiement'
    | '/admin/'
    | '/restaurants/$restoId/plats/$platId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdressesRoute: typeof AdressesRoute
  AideRoute: typeof AideRoute
  CheckoutRoute: typeof CheckoutRoute
  CommandesRoute: typeof CommandesRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConnexionRoute: typeof ConnexionRoute
  ContactRoute: typeof ContactRoute
  DevenirLivreurRoute: typeof DevenirLivreurRoute
  DevenirRestoRoute: typeof DevenirRestoRoute
  FideliteRoute: typeof FideliteRoute
  LivreurRoute: typeof LivreurRoute
  MboaAiRoute: typeof MboaAiRoute
  MboapassRoute: typeof MboapassRoute
  ParrainageRoute: typeof ParrainageRoute
  ProfilRoute: typeof ProfilRoute
  RechercheRoute: typeof RechercheRoute
  RestaurantRoute: typeof RestaurantRoute
  SuiviRoute: typeof SuiviRouteWithChildren
  TableeRoute: typeof TableeRouteWithChildren
  CategorieSlugRoute: typeof CategorieSlugRoute
  RestaurantsRestoIdRoute: typeof RestaurantsRestoIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tablee': {
      id: '/tablee'
      path: '/tablee'
      fullPath: '/tablee'
      preLoaderRoute: typeof TableeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi': {
      id: '/suivi'
      path: '/suivi'
      fullPath: '/suivi'
      preLoaderRoute: typeof SuiviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parrainage': {
      id: '/parrainage'
      path: '/parrainage'
      fullPath: '/parrainage'
      preLoaderRoute: typeof ParrainageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mboapass': {
      id: '/mboapass'
      path: '/mboapass'
      fullPath: '/mboapass'
      preLoaderRoute: typeof MboapassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mboa-ai': {
      id: '/mboa-ai'
      path: '/mboa-ai'
      fullPath: '/mboa-ai'
      preLoaderRoute: typeof MboaAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livreur': {
      id: '/livreur'
      path: '/livreur'
      fullPath: '/livreur'
      preLoaderRoute: typeof LivreurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fidelite': {
      id: '/fidelite'
      path: '/fidelite'
      fullPath: '/fidelite'
      preLoaderRoute: typeof FideliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devenir-resto': {
      id: '/devenir-resto'
      path: '/devenir-resto'
      fullPath: '/devenir-resto'
      preLoaderRoute: typeof DevenirRestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devenir-livreur': {
      id: '/devenir-livreur'
      path: '/devenir-livreur'
      fullPath: '/devenir-livreur'
      preLoaderRoute: typeof DevenirLivreurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes': {
      id: '/commandes'
      path: '/commandes'
      fullPath: '/commandes'
      preLoaderRoute: typeof CommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide': {
      id: '/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adresses': {
      id: '/adresses'
      path: '/adresses'
      fullPath: '/adresses'
      preLoaderRoute: typeof AdressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tablee/paiement': {
      id: '/tablee/paiement'
      path: '/paiement'
      fullPath: '/tablee/paiement'
      preLoaderRoute: typeof TableePaiementRouteImport
      parentRoute: typeof TableeRoute
    }
    '/suivi/$orderId': {
      id: '/suivi/$orderId'
      path: '/$orderId'
      fullPath: '/suivi/$orderId'
      preLoaderRoute: typeof SuiviOrderIdRouteImport
      parentRoute: typeof SuiviRoute
    }
    '/restaurants/$restoId': {
      id: '/restaurants/$restoId'
      path: '/restaurants/$restoId'
      fullPath: '/restaurants/$restoId'
      preLoaderRoute: typeof RestaurantsRestoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorie/$slug': {
      id: '/categorie/$slug'
      path: '/categorie/$slug'
      fullPath: '/categorie/$slug'
      preLoaderRoute: typeof CategorieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/zones': {
      id: '/admin/zones'
      path: '/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AdminZonesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/restaurants': {
      id: '/admin/restaurants'
      path: '/restaurants'
      fullPath: '/admin/restaurants'
      preLoaderRoute: typeof AdminRestaurantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/livreurs': {
      id: '/admin/livreurs'
      path: '/livreurs'
      fullPath: '/admin/livreurs'
      preLoaderRoute: typeof AdminLivreursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/litiges': {
      id: '/admin/litiges'
      path: '/litiges'
      fullPath: '/admin/litiges'
      preLoaderRoute: typeof AdminLitigesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/restaurants/$restoId/plats/$platId': {
      id: '/restaurants/$restoId/plats/$platId'
      path: '/plats/$platId'
      fullPath: '/restaurants/$restoId/plats/$platId'
      preLoaderRoute: typeof RestaurantsRestoIdPlatsPlatIdRouteImport
      parentRoute: typeof RestaurantsRestoIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminLitigesRoute: typeof AdminLitigesRoute
  AdminLivreursRoute: typeof AdminLivreursRoute
  AdminRestaurantsRoute: typeof AdminRestaurantsRoute
  AdminZonesRoute: typeof AdminZonesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminLitigesRoute: AdminLitigesRoute,
  AdminLivreursRoute: AdminLivreursRoute,
  AdminRestaurantsRoute: AdminRestaurantsRoute,
  AdminZonesRoute: AdminZonesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SuiviRouteChildren {
  SuiviOrderIdRoute: typeof SuiviOrderIdRoute
}

const SuiviRouteChildren: SuiviRouteChildren = {
  SuiviOrderIdRoute: SuiviOrderIdRoute,
}

const SuiviRouteWithChildren = SuiviRoute._addFileChildren(SuiviRouteChildren)

interface TableeRouteChildren {
  TableePaiementRoute: typeof TableePaiementRoute
}

const TableeRouteChildren: TableeRouteChildren = {
  TableePaiementRoute: TableePaiementRoute,
}

const TableeRouteWithChildren =
  TableeRoute._addFileChildren(TableeRouteChildren)

interface RestaurantsRestoIdRouteChildren {
  RestaurantsRestoIdPlatsPlatIdRoute: typeof RestaurantsRestoIdPlatsPlatIdRoute
}

const RestaurantsRestoIdRouteChildren: RestaurantsRestoIdRouteChildren = {
  RestaurantsRestoIdPlatsPlatIdRoute: RestaurantsRestoIdPlatsPlatIdRoute,
}

const RestaurantsRestoIdRouteWithChildren =
  RestaurantsRestoIdRoute._addFileChildren(RestaurantsRestoIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdressesRoute: AdressesRoute,
  AideRoute: AideRoute,
  CheckoutRoute: CheckoutRoute,
  CommandesRoute: CommandesRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConnexionRoute: ConnexionRoute,
  ContactRoute: ContactRoute,
  DevenirLivreurRoute: DevenirLivreurRoute,
  DevenirRestoRoute: DevenirRestoRoute,
  FideliteRoute: FideliteRoute,
  LivreurRoute: LivreurRoute,
  MboaAiRoute: MboaAiRoute,
  MboapassRoute: MboapassRoute,
  ParrainageRoute: ParrainageRoute,
  ProfilRoute: ProfilRoute,
  RechercheRoute: RechercheRoute,
  RestaurantRoute: RestaurantRoute,
  SuiviRoute: SuiviRouteWithChildren,
  TableeRoute: TableeRouteWithChildren,
  CategorieSlugRoute: CategorieSlugRoute,
  RestaurantsRestoIdRoute: RestaurantsRestoIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
