/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TableeRouteImport } from './routes/tablee'
import { Route as SuiviRouteImport } from './routes/suivi'
import { Route as MboaAiRouteImport } from './routes/mboa-ai'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as AdressesRouteImport } from './routes/adresses'
import { Route as IndexRouteImport } from './routes/index'

const TableeRoute = TableeRouteImport.update({
  id: '/tablee',
  path: '/tablee',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviRoute = SuiviRouteImport.update({
  id: '/suivi',
  path: '/suivi',
  getParentRoute: () => rootRouteImport,
} as any)
const MboaAiRoute = MboaAiRouteImport.update({
  id: '/mboa-ai',
  path: '/mboa-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdressesRoute = AdressesRouteImport.update({
  id: '/adresses',
  path: '/adresses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adresses': typeof AdressesRoute
  '/connexion': typeof ConnexionRoute
  '/mboa-ai': typeof MboaAiRoute
  '/suivi': typeof SuiviRoute
  '/tablee': typeof TableeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adresses': typeof AdressesRoute
  '/connexion': typeof ConnexionRoute
  '/mboa-ai': typeof MboaAiRoute
  '/suivi': typeof SuiviRoute
  '/tablee': typeof TableeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adresses': typeof AdressesRoute
  '/connexion': typeof ConnexionRoute
  '/mboa-ai': typeof MboaAiRoute
  '/suivi': typeof SuiviRoute
  '/tablee': typeof TableeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adresses'
    | '/connexion'
    | '/mboa-ai'
    | '/suivi'
    | '/tablee'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adresses' | '/connexion' | '/mboa-ai' | '/suivi' | '/tablee'
  id:
    | '__root__'
    | '/'
    | '/adresses'
    | '/connexion'
    | '/mboa-ai'
    | '/suivi'
    | '/tablee'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdressesRoute: typeof AdressesRoute
  ConnexionRoute: typeof ConnexionRoute
  MboaAiRoute: typeof MboaAiRoute
  SuiviRoute: typeof SuiviRoute
  TableeRoute: typeof TableeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tablee': {
      id: '/tablee'
      path: '/tablee'
      fullPath: '/tablee'
      preLoaderRoute: typeof TableeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi': {
      id: '/suivi'
      path: '/suivi'
      fullPath: '/suivi'
      preLoaderRoute: typeof SuiviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mboa-ai': {
      id: '/mboa-ai'
      path: '/mboa-ai'
      fullPath: '/mboa-ai'
      preLoaderRoute: typeof MboaAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adresses': {
      id: '/adresses'
      path: '/adresses'
      fullPath: '/adresses'
      preLoaderRoute: typeof AdressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdressesRoute: AdressesRoute,
  ConnexionRoute: ConnexionRoute,
  MboaAiRoute: MboaAiRoute,
  SuiviRoute: SuiviRoute,
  TableeRoute: TableeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
